Merge release branch into master (microsoft/vscode-python#10258)
* Davidkutu/ds interactive window focus fix (microsoft/vscode-python#9895)

* Fixed the focus on the interactive window
when pressing ctrl +2

* the new prop 'focusPending' needs to change in
order to give focus

* added functional test

* In test: force focus to buttons to take it away from

* finished the functional test

* updated changelog

* deleted bug#.md

* Fix variables on mac and linux (microsoft/vscode-python#9897) (microsoft/vscode-python#9903)

* Fix regexes to work on other platforms

* Fix data frame viewer

* Fix linter problems

Co-authored-by: Don Jayamanne <don.jayamanne@yahoo.com>

Co-authored-by: Don Jayamanne <don.jayamanne@yahoo.com>

* Fix focusing of cells when navigating cells using up/down arrow (microsoft/vscode-python#9885) (microsoft/vscode-python#9908)

For microsoft/vscode-python#9884

* Disable webHostNotebook experiment and fix name of exp (microsoft/vscode-python#9894) (microsoft/vscode-python#9907)

Disable an experiment
Fix name of an existing experiment

* Davidkutu/ds scrapbook render fix (microsoft/vscode-python#9912)

* check if we support mimetypes before
loading html to avoid crashing

* Silently skip rendering of the scapbook mime types

* added news file

* updated changelog and deleted news file

* Disable the terminal activation experiment (microsoft/vscode-python#9937)

Disable until next release of VSC (for hidden terminals).
Disabled because a terminal gets displayed to the user and then hidden (doesn't happen in insiders, we will need to wait for their new API to hide terms)

* Notebook should use kernel from metadata (microsoft/vscode-python#9936)

For microsoft/vscode-python#9927
* Notebook should use kernel from metadata
* Fix formatting

* Port server cache fix to release (microsoft/vscode-python#9932)

* Port variable restart fix (microsoft/vscode-python#9938)

* Fix variable explorer when restarting a kernel (microsoft/vscode-python#9931)

* Make sure to clear variable list on reset

* Add news entry

* Update changelog

* Update changelog

* Do not override kernels info in other notebooks (microsoft/vscode-python#9958)

For microsoft/vscode-python#9951, microsoft/vscode-python#9950, microsoft/vscode-python#9949
* Do not override kernels info in other notebooks
* Fixes

* Disables the use of a terminal to activate an environment (microsoft/vscode-python#9967)

* Disables the use of a terminal to activate an environment
* Fix tests
* Fix linter

* Port server name fix to release (microsoft/vscode-python#9970)

* When starting Jupyter activate conda env (microsoft/vscode-python#9972)

* If interpreter is provided use that to check if is conda environment
* Fix tests
For microsoft/vscode-python#9973
Currently conda isn't getting activated when auto starting Jupyter server.

* Porting K8 fix to release (microsoft/vscode-python#9987)

* Update version and changelog date for release (microsoft/vscode-python#10022)

* Ignore FS errors from stat() in some cases. (microsoft/vscode-python#10032)

(for microsoft/vscode-python#9901)

The earlier FS code ignored errors in a couple of situations. Recent changes inadvertently stopped ignoring them. This change restores the earlier behavior (and adds logging of the errors).

This is a backport of microsoft/vscode-python#10021.

* Update chang log (microsoft/vscode-python#10041)

* Install jupyter instead of installing kernel spec (microsoft/vscode-python#10080) (microsoft/vscode-python#10083)

* Install jupyter instead of installing kernel spec
For microsoft/vscode-python#10071

* Fix for zh-tw loading issue. (microsoft/vscode-python#10085) (microsoft/vscode-python#10089)

* Update version and changelog for point release. (microsoft/vscode-python#10091)

* Update version and changelog for point release.

* Add note to change log.

* Port fixes for second point release. (microsoft/vscode-python#10146)

* Better messaging on notebook fail (microsoft/vscode-python#10056)

* Install jupyter instead of installing kernel spec (microsoft/vscode-python#10080)

* Install jupyter instead of installing kernel spec
For microsoft/vscode-python#10071

* Eliminate variable value when computing data frame info (microsoft/vscode-python#10081)

* Fix ndarray types to be viewable again (microsoft/vscode-python#10093)

* Eliminate variable value when computing data frame info

* Fix ndarrays to work again
Add test to make sure we don't regress this again

* Rchiodo/kernel telemetry (microsoft/vscode-python#10115)

* Add duration to select local/remote kernel

* Add notebook language telemetry

* Add news entries

* microsoft/vscode-python#9883 telemetry

* News entry

* Another spot for kernel spec failure

* Add telemetry on product install

* Fix install telemetry

* Undo launch.json change

* Handle other cases

* Better way to handle case

* Wrong event for jupyter install

* Fix unit tests

* Clear variables when restarting regardless if visible or not (microsoft/vscode-python#10117)

* Use different method for checking if kernelspec is available (microsoft/vscode-python#10114)

* Use different method for checking if kernelspec is available

* Fix unit tests

* More logging for kernelspec problems (microsoft/vscode-python#10132)

* More logging for kernelspec problems

* Actually capture the exception on the new code

* Not actually using output if first exception still there.

* Actually only return output on one of the expected calls.

* Fix nightly flake

* Check our saved jupyter interpreters before allowing any of them to be used as active interpreters (microsoft/vscode-python#10113)

* Update changelog and package.json

* Missing part of changelog

* Fix tests and linter problems

Co-authored-by: Ian Huff <ian.huff@gmail.com>
Co-authored-by: Don Jayamanne <don.jayamanne@yahoo.com>

* Cherry pick more fixes for feb point2 (microsoft/vscode-python#10183)

* Ensure DS auto start code is non-blocking (microsoft/vscode-python#10171)

* Perf fixes
* Add news entry

* Include interperter name in message (microsoft/vscode-python#10174)

For microsoft/vscode-python#10071
Fix to ensure interpreter is included in message, here's the actual message seen by the user.

Error: Jupyter cannot be started. Error attempting to locate jupyter: 'Kernelspec' module not installed in the selected interpreter ({0}).

Note the {0}

* Ignore display name when searching interpreters (microsoft/vscode-python#10175)

Partial fix for microsoft/vscode-python#10173
Comparing against path of interpreter alone is sufficient.

Figured there's no harm in trying to minimise occurrences of dup kernels (basically just compare against python executable path, as thats sufficient and always accurate)

Display name:

Can change from version to version of Python extension (i.e. it shouldn't have been used as a unique identifier)
Display name can change after extension loads and more information about interpreter is available.

* Track cold/warm times to execute notebook cells (microsoft/vscode-python#10180)

For microsoft/vscode-python#10176

* fix SVG mimetype name (microsoft/vscode-python#10181) (microsoft/vscode-python#10185)

* Update change log

* Some more ds telemetry (microsoft/vscode-python#10218)

* Add telemetry to capture perceived time taken to start jupyter and run cell (microsoft/vscode-python#10217)

* Add telemetry
* Only for nb
For microsoft/vscode-python#10098
For microsoft/vscode-python#10212

* Fix change log

* Fix linter

* Update date in change log

* Point release with fix for Issue 10250 (microsoft/vscode-python#10254)

* Fix to return env variables of interpreter that is not current interpreter (microsoft/vscode-python#10251)
For microsoft/vscode-python#10250
* Bug fix
* Update change log
* Fix date
* Oops
* Fix linter

* Clean up

* More clean up

* Some more text fixes

Co-authored-by: David Kutugata <dakutuga@microsoft.com>
Co-authored-by: Rich Chiodo <rchiodo@users.noreply.github.com>
Co-authored-by: Don Jayamanne <don.jayamanne@yahoo.com>
Co-authored-by: Ian Huff <ian.huff@gmail.com>
Co-authored-by: Eric Snow <ericsnowcurrently@gmail.com>