Modernize yarn invocations (#4704)
This change addresses CI failures of the form:

```
yarn install v1.22.22
warning ../package.json: No license field
error `install` has been replaced with `add` to add new dependencies. Run "yarn add install" instead.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Process completed with exit code 1.
```

Example run:
https://github.com/posit-dev/positron/actions/runs/10896318741/job/30235932351

The fix is twofold:
- Install `yarn` with `corepack` (the recommended mechanism as of Node
20)
- Use `yarn add` instead of `yarn install` as recommended in the message

### QA Notes

No product change; changes to CI files only