fix linux debian package version format
The deb-version has a specific format, one aspect of which is no spaces.

```
Error: Command failed: fakeroot dpkg-deb -b positron-amd64 deb
dpkg-deb: error: parsing file 'positron-amd64/DEBIAN/control' near line 2 package 'positron':
 'Version' field value '2024.11.0-1729291046 build 0': version string has embedded spaces
```

https://linux.die.net/man/5/deb-version

So, the version we'll include in the package info will be `<version>+<build>-<revision>`