Revert some changes
From https://github.com/microsoft/vscode/commit/af5cf640d81fd44b2ec16a5b0bf6d2939a1eb4be

Work around this error:

```
 Error: src/playwrightDriver.ts(235,20): error TS2769: No overload matches this call.
  Overload 1 of 2, '(pageFunction: PageFunction<IWindowDriver[], T>, arg: IWindowDriver[]): Promise<T>', gave the following error.
    Type 'JSHandle<IWindowDriver>' is missing the following properties from type 'IWindowDriver': setValue, isActiveElement, getElements, getElementXY, and 8 more.
  Overload 2 of 2, '(pageFunction: PageFunction<void, T>, arg?: any): Promise<T>', gave the following error.
    Argument of type 'PageFunction<IWindowDriver[], T>' is not assignable to parameter of type 'PageFunction<void, T>'.
      Type '(arg: IWindowDriver[]) => T | Promise<T>' is not assignable to type 'PageFunction<void, T>'.
        Type '(arg: IWindowDriver[]) => T | Promise<T>' is not assignable to type '(arg: void) => T | Promise<T>'.
          Types of parameters 'arg' and 'arg' are incompatible.
            Type 'void' is not assignable to type 'IWindowDriver[]'.
```