use non-null assertion on `this._webview.value`
Uses of `this._webview.value` which occur after `this.isActive()` checks can be asserted to be non-null, since `this.isActive()` checks that `this._webview.value` exists.

In dev/debug builds, we don't need to assert non-null, but in release builds, compilation errors with:

```
webviewPlotClient.ts(127,3): Object is possibly 'undefined'.
webviewPlotClient.ts(141,3): Object is possibly 'undefined'.
webviewPlotClient.ts(154,3): Object is possibly 'undefined'.
webviewPlotClient.ts(170,3): Object is possibly 'undefined'.
```