fix Run App for Gradio apps (#5590)
### Summary

- Addresses https://github.com/posit-dev/positron/issues/5459
- Companion Gradio Issue
https://github.com/gradio-app/gradio/issues/10093
- Companion Gradio PR https://github.com/gradio-app/gradio/pull/10094
- Re-enables `Python - Verify Basic Gradio App [C903307]`

#### localhost ValueError
https://github.com/gradio-app/gradio/pull/10094 addresses the following
error described in #5459

```
Traceback (most recent call last):
  File "/Users/christophermead/posit/qa-example-content/workspaces/python_apps/gradio_example/gradio_example.py", line 5, in <module>
    demo.launch()
  File "/Users/christophermead/.pyenv/versions/3.10.12/lib/python3.10/site-packages/gradio/blocks.py", line 2582, in launch
    raise ValueError(
ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to allow access to localhost.
```

We'll need to wait for [Gradio
5.8.0](https://github.com/gradio-app/gradio/pull/10082) before we can
confirm that this error is fixed -- **edit: 5.8.0 has been released**!
This error occurs before the [CSS styling
issue](https://github.com/posit-dev/positron/issues/5459#issuecomment-2515466211)
can be seen. A manual patch to gradio is currently needed in order to
reach this second issue.

#### Failure to load styles
Our use of `GRADIO_ROOT_PATH` is no longer needed and also no longer
works since the underlying issue was resolved in [Gradio
5.7.0](https://github.com/gradio-app/gradio/pull/9970), via
https://github.com/gradio-app/gradio/pull/9822. The related code is
being removed in this PR.

### QA Notes

The [gradio example
app](https://github.com/posit-dev/qa-example-content/tree/main/workspaces/python_apps/gradio_example)
should now work in Web and Desktop.