use posit cdn for python tests download url (#6496)
We no longer publish the release binaries as assets, but the
`downloadAndUnzipPositron()` function still assumes that we do.

This PR updates the script to use the CDN url so we shouldn't see this
error anymore when running Python extension MacOS tests:

```
Run GabrielBB/xvfb-action@v1.7
/Users/runner/hostedtoolcache/node/20.12.1/arm64/bin/npm run testDebugger

> python@2025.99.0-dev testDebugger
> node ./out/test/testBootstrap.js ./out/test/debuggerTest.js

Test server listening on port 49253
****************************************************************************************************
Start Debugger tests
Using Github PAT from environment variable POSITRON_GITHUB_PAT.
End Debugger tests (with errors) Error: No asset found with suffix .dmg for platform darwin
    at downloadAndUnzipPositron (/Users/runner/work/positron/positron/path with spaces/extensions/positron-python/out/test/positron/testElectron.js:197:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runTests (/Users/runner/work/positron/positron/path with spaces/extensions/positron-python/out/test/positron/testElectron.js:269:63)
Exiting with test failures
Killing VSC
Error: The process '/Users/runner/hostedtoolcache/node/20.12.1/arm64/bin/npm' failed with exit code 1
```

### QA Notes

Python Mac OS tests should now pass locally and in CI.