Merge 2025.03 to main to run python ci tests on prerelease branches and pin ipykernel (#6564)
Merge changes from prerelease/2025.03 to main

----
Run python ci tests on prerelease branches and pin ipython to <=8.31.0 

### Summary
- Python CI tests will now run on prerelease branch PRs starting from
`prerelease/2025.03`
- Python CI tests will run when commits are pushed to prerelease
branches
- pins ipython to <=8.31.0 to avoid a test failure occurring in the
Python IPyKernel tests on this branch and on the main branch
```
FAILED
python_files/posit/positron/tests/test_positron_ipkernel.py::test_console_traceback
AttributeError: 'AutoFormattedTB' object has no attribute 'Colors'
```
- pulls in https://github.com/posit-dev/positron/pull/6496 to fix up
python CI tests on mac

---------

Signed-off-by: sharon <sharon-wang@users.noreply.github.com>
Co-authored-by: Daniel Falbel <dfalbel@gmail.com>
Co-authored-by: Marie Idleman <marie.idleman@posit.co>
Co-authored-by: Jon Vanausdeln <jonv@live.com>
Co-authored-by: Melissa Barca <5323711+melissa-barca@users.noreply.github.com>
Co-authored-by: sharon <sharon-wang@users.noreply.github.com>
Co-authored-by: Isabel Zimmerman <54685329+isabelizimm@users.noreply.github.com>