Work around dev typescript issue
Fixes

```
Error: src/areas/positron/plots/plots.test.ts(92,82): error TS2345: Argument of type 'Buffer' is not assignable to parameter of type 'string | ArrayBufferView'.
  Type 'Buffer' is not assignable to type 'Uint8Array | DataView'.
    Type 'Buffer' is not assignable to type 'Uint8Array'.
      The types returned by 'entries()' are incompatible between these types.
        Type 'IterableIterator<[number, number]>' is missing the following properties from type 'ArrayIterator<[number, number]>': map, filter, take, drop, and 8 more.
Error: src/areas/positron/plots/plots.test.ts(135,73): error TS2345: Argument of type 'Buffer' is not assignable to parameter of type 'string | ArrayBufferView'.
  Type 'Buffer' is not assignable to type 'Uint8Array | DataView'.
    Type 'Buffer' is not assignable to type 'Uint8Array'.
      The types returned by 'entries()' are incompatible between these types.
        Type 'IterableIterator<[number, number]>' is missing the following properties from type 'ArrayIterator<[number, number]>': map, filter, take, drop, and 8 more.
Error: src/areas/positron/plots/plots.test.ts(314,70): error TS2345: Argument of type 'Buffer' is not assignable to parameter of type 'string | ArrayBufferView'.
  Type 'Buffer' is not assignable to type 'Uint8Array | DataView'.
    Type 'Buffer' is not assignable to type 'Uint8Array'.
      The types returned by 'entries()' are incompatible between these types.
        Type 'IterableIterator<[number, number]>' is missing the following properties from type 'ArrayIterator<[number, number]>': map, filter, take, drop, and 8 more.
```